[package]
name = "gamemaker-rust-dll-example"
version = "0.1.0"
authors = ["GirkovArpa <girkovarpa@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc ="*"

[lib]
crate-type = ["cdylib"]